"""contains constants used across modules"""

# --- sync command ---
ARTIST_LIST_DELIMITERS = r",| & |vs\.|\n|ft\.|feat\.|featuring| / |; "
NUMBER_OF_RESULTS_PER_QUERY = 5
USE_RB_TO_SPOTIFY_MATCHES_CACHE = True
USE_SPOTIFY_SEARCH_RESULTS_CACHE = True
DEBUG_SIMILARITY = False
MINIMUM_SIMILARITY_THRESHOLD = 0.95
RESOLVE_FAILED_MATCHES = False

# --- id command ---
FORCE_REDO_SHAZAM = False
NUM_SHAZAM_MATCHES_THRESHOLD = 5
SHOW_URL_IN_SHAZAM_OUTPUT = False
